# Users
User.create(username: 'torianne', email: 'torianne@gmail.com', password: 'password')
User.create(username: 'kevcraw', email: 'kevcraw@gmail.com', password: 'password1')
User.create(username: 'coachflu', email: 'coachflu@gmail.com', password: 'password2')
User.create(username: 'torrnado', email: 'torrnado@gmail.com', password: 'tornado1')

# Breweries
Brewery.create(name: 'Yuengling Brewery')
Brewery.create(name: 'Guinness')
Brewery.create(name: 'Anheuser-Busch')
Brewery.create(name: 'New Belgium Brewing Company')
Brewery.create(name: 'Belching Beaver Brewery')
Brewery.create(name: 'Goose Island')
Brewery.create(name: 'Karl Strauss Brewing Company')

# Beers
Beer.create(name: 'Traditional Lager', beer_type: 'Lager - American Amber/Red', ibu: 16, abv: 4.5, user_id: 1, brewery_id: 1)
Beer.create(name: 'Light Lager', beer_type: 'Lager - American Light', ibu: 10, abv: 3.8, user_id: 1, brewery_id: 1)
Beer.create(name: 'Guinness Draught', beer_type: 'Stout - Irish Dry', ibu: 45, abv: 4.2, user_id: 1, brewery_id: 2)
Beer.create(name: 'Budweiser', beer_type: 'Lager', ibu: 12, abv: 5.0, user_id: 4, brewery_id: 3)
Beer.create(name: 'Busch Light', beer_type: 'Lager - American Light', ibu: 0, abv: 4.1, user_id: 4, brewery_id: 3)
Beer.create(name: 'Fat Tire', beer_type: 'Red Ale - American Amber/Red', ibu: 22, abv: 5.2, user_id: 1, brewery_id: 4)
Beer.create(name: 'Peanut Butter Milk Stout', beer_type: 'Milk Stout', ibu: 30, abv: 5.3, user_id: 2, brewery_id: 5)
Beer.create(name: 'Mexican Chocolate Peanut Butter Stout', beer_type: 'Milk Stout', ibu: 28, abv: 7.5, user_id: 2, brewery_id: 5)
Beer.create(name: 'Me So Honey Blonde', beer_type: 'Honey Wheat Ale', ibu: 25, abv: 5.5, user_id: 3, brewery_id: 5)
Beer.create(name: 'Beavers Milk Stout Nitro', beer_type: 'Milk Stout', ibu: 30, abv: 5.3, user_id: 2, brewery_id: 5)
Beer.create(name: 'Green Line', beer_type: 'American Pale Ale', ibu: 30, abv: 5.4, user_id: 3, brewery_id: 6)
Beer.create(name: '312', beer_type: 'Urban Wheat Ale', ibu: 18, abv: 4.2, user_id: 1, brewery_id: 6)
Beer.create(name: 'Bourbon County Brand Stout 2018', beer_type: 'Bourbon Barrel-Aged Imperial Stout', ibu: 60, abv: 14.7, user_id: 2, brewery_id: 6)
Beer.create(name: 'Goose IPA', beer_type: 'Indian Pale Ale', ibu: 55, abv: 5.9, user_id: 3, brewery_id: 6)
Beer.create(name: 'Pintail Pale Ale', beer_type: 'American Pale Ale', ibu: 47, abv: 5.3, user_id: 3, brewery_id: 7)
Beer.create(name: 'Wreck Alley Imperial Stout', beer_type: 'Russian Imperial Stout', ibu: 45, abv: 9.0, user_id: 2, brewery_id: 7)
Beer.create(name: 'Peanut Butter Cup Porter', beer_type: 'Robust Brown Porter', ibu: 30, abv: 5.6, user_id: 4, brewery_id: 7)
Beer.create(name: 'Red Trolley Ale', beer_type: 'Irish Style Red Ale', ibu: 17, abv: 5.8, user_id: 1, brewery_id: 7)
Beer.create(name: 'Columbia Street Amber', beer_type: 'Session Lager', ibu: 18, abv: 4.5, user_id: 1, brewery_id: 7)
